In [16]:
import numpy as np
a=np.array([[1,2],[4,5]])
b=np.array([[3,7],[9,6]])
print("MATRIX OPERATIONS")
print(f"MATRIX A:\n{a}")
print(f"MATRIX B:\n{b}")
print(f"MATRIX ADDITION:\n{a+b}")
print(f"MATRIX SUBTRACTION:\n{a-b}")
print(f"MATRIX MULTIPLICATION:\n{a*b}")
print(f"MATRIX TRANSPOSE:\n{a.T}")

MATRIX OPERATIONS
MATRIX A:
[[1 2]
 [4 5]]
MATRIX B:
[[3 7]
 [9 6]]
MATRIX ADDITION:
[[ 4  9]
 [13 11]]
MATRIX SUBTRACTION:
[[-2 -5]
 [-5 -1]]
MATRIX MULTIPLICATION:
[[ 3 14]
 [36 30]]
MATRIX TRANSPOSE:
[[1 4]
 [2 5]]
