In [3]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
U,S,VT = np.linalg.svd(x)
n_components=2
x_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("original matrix:")
print(x)
print("\nreconstructed matrix:")
print(x_reconstructed)

original matrix:
[[1 2 3]
 [4 5 6]]

reconstructed matrix:
[[1. 2. 3.]
 [4. 5. 6.]]
